import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy Information", description: "How this website handles anonymous analytics and optional newsletter subscriptions.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return (
    <article className="mx-auto max-w-4xl space-y-8 px-4 py-12 sm:px-8 sm:py-16">
      <header><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#986f35]">Website information</p><h1 className="mt-3 font-serif text-4xl text-[#17253d]">Privacy information</h1><p className="mt-3 text-sm leading-relaxed text-slate-600">This page describes the limited optional analytics and newsletter processing provided by this website. It should be reviewed against the firm’s applicable legal obligations before production launch.</p></header>
      <section className="space-y-3"><h2 className="font-serif text-2xl">Anonymous visitor statistics</h2><p className="text-sm leading-7 text-slate-700">Analytics are off unless you select “Allow analytics”. If allowed, this site stores a random first-party browser identifier for up to one year and records public page paths and timestamps. It does not store IP addresses, user-agent strings, device fingerprints, query strings, consultation form content, names, or email addresses in analytics.</p><p className="text-sm leading-7 text-slate-700">A new visit is counted when the same browser returns at least 24 hours after its previous counted visit. “Unique browser” is not the same as a person: different devices, cleared browser storage, blocked cookies, or declined consent can change these estimates. Common automated user agents are excluded, but bot detection is not perfect. Analytics records are retained for up to 13 months.</p><p className="text-sm leading-7 text-slate-700">You can change your choice using the “Privacy choices” control at the bottom of the page. Declining or withdrawing consent does not limit access to the website. Withdrawal stops future collection and removes the browser identifier from your browser; past aggregate records may remain in reports until the retention period expires.</p></section>
      <section className="space-y-3"><h2 className="font-serif text-2xl">Nyaycast email updates</h2><p className="text-sm leading-7 text-slate-700">Newsletter signup is optional and separate from consultation forms. If enabled, the submitted email address is stored as pending until you confirm by email. Confirmation links expire after 24 hours. Confirmed subscribers can unsubscribe from any email; suppression records are kept to honor that choice. Newsletter details are not used as visitor analytics.</p></section>
      <section className="space-y-3"><h2 className="font-serif text-2xl">Consultation preparation tool</h2><p className="text-sm leading-7 text-slate-700">Checklist selections remain temporarily in the page and are not transmitted to the server or stored after leaving. Do not enter confidential matter details into website forms or tools unless specifically requested through an appropriate channel.</p></section>
      <p className="border-t border-[#17253d]/15 pt-5 text-xs leading-relaxed text-slate-500">The website’s legal information is general in nature, is not legal advice, and does not create an advocate-client relationship.</p>
    </article>
  );
}